title: Nikolaj Foghs blog
email: nikolajfogh@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Some various ramblings about software and hardware development
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  nfogh

theme: minima
plugins:
  - jekyll-feed
